### ISSUE TITLE
teambition访问

### ISSUE THREAD

**Issue by vissible** [CNMan/unbound.conf#10]
访问teambition需要forward-zone里再添加个teambition.net。

**Comment by CNMan** [comment]
请反馈到 https://github.com/felixonmars/dnsmasq-china-list

**Comment by CNMan** [comment]
@vissible 帮忙反馈到 https://github.com/felixonmars/dnsmasq-china-list/issues/146 后已被添加
https://github.com/felixonmars/dnsmasq-china-list/commit/4f29fe356873ba69b800d595bf03a8593b2b79de
