### ISSUE TITLE
要是别人没有E盘 可以更方便的办法

### ISSUE THREAD

**Issue by lrinQVQ** [CNMan/unbound.conf#14]
推荐wget到当前执行文件夹
`dirname $0`
这样不是更方便嘛Orz

**Comment by CNMan** [comment]
因为配置里面涉及到绝对路径，只能下载后自己修改了:)
嫌麻烦可以下载傻瓜包，适用只有C盘的情形，那个什么都不用改

**Comment by lrinQVQ** [comment]
23333333好吧

**Comment by CliffCharles** [comment]
我想让localdns.cmd和localcmd-update.cmd开机自启动，怎么设置啊？

**Comment by CNMan** [comment]
@CliffCharles 
复制localdns.cmd到C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\(Vista+)或C:\Documents and Settings\All Users\Start Menu\Programs\Startup(XP-)

localcmd-update.cmd不要开机自启，dns如果没先正常工作，会导致下载失败，配置有可能出错。

**Comment by CliffCharles** [comment]
好的

**Comment by CNMan** [comment]
https://github.com/CNMan/unbound.conf/commit/9c906fd16765e42463ce7ab7b12183856d8eb437
更新了一下，这里的与傻瓜包保持一致，都搞在C盘
C盘大家都有吧？^_^
