### ISSUE TITLE
dnscrypt-proxy.exe经常停止工作

### ISSUE THREAD

**Issue by CliffCharles** [CNMan/unbound.conf#15]
![default](https://cloud.githubusercontent.com/assets/24654894/23215211/86e594e4-f94c-11e6-9d7a-90432c2f4dd8.PNG)
电脑运行几个小时后，dnscrypt-proxy.exe不稳定，经常停止工作怎么办?

**Comment by CNMan** [comment]
网络异常的时候会这样，给官方反馈过，无果:(
 https://github.com/jedisct1/dnscrypt-proxy/issues/537
临时解决方案：依次运行这两个批处理重启一下
localdns-stop.cmd
localdns.cmd

**Comment by CliffCharles** [comment]
嗯，好的
