### ISSUE TITLE
检查unbound配置文件报错

### ISSUE THREAD

**Issue by idolyuri** [CNMan/unbound.conf#18]
暂时用旧的local-zone了~
![image](https://cloud.githubusercontent.com/assets/8514351/24557514/8692049c-166a-11e7-81d1-fa6bd4fd750c.png)

**Comment by CNMan** [comment]
上游数据错误，下个commit暂时先删掉这一条，等上游修正再恢复吧
https://github.com/lennylxx/ipv6-hosts/issues/104

**Comment by CNMan** [comment]
fixed https://github.com/CNMan/unbound.conf/commit/c175f3d878a1968a69de884f71fbebd0aafbd675
