### ISSUE TITLE
请科学加速相关google firebase的云服务器端点

### ISSUE THREAD

**Issue by anlexN** [CNMan/unbound.conf#19]
我个人表示对此工程欣赏，但是最近发现上传文件到google firebase 云服务器的时候，总是ETIMEOUT, 连接超时，请作者科学加速一下，比如其中一个云端点：cloudfuntions.net 
另外youtube.com也能加速一下就更好了，因为看视频的时候总卡顿
作者请努力！
另外我很乐意帮助，您可以教一下可以科学上网相关的技术，谢谢！

**Comment by CNMan** [comment]
只能保证解析正确，不能保证解析准确，本项目并不维护数据源。

**Comment by anlexN** [comment]
问题是事实上我并没有感觉到解析正确，请问您可以解释一下吗？
