### ISSUE TITLE
hosts转换命令

### ISSUE THREAD

**Issue by CNMan** [CNMan/unbound.conf#2]
``` bash
wget -N http://unbound.nlnetlabs.nl/svn/trunk/contrib/build-unbound-localzone-from-hosts.pl
chmod +x build-unbound-localzone-from-hosts.pl
```

修改一下`build-unbound-localzone-from-hosts.pl`里的默认文件位置

```
my $hostsfile = 'hosts';
my $localzonefile = 'localzone.conf.new';
```

``` bash
wget -N https://raw.githubusercontent.com/racaljk/hosts/master/hosts
./build-unbound-localzone-from-hosts.pl
echo '# Converted from https://github.com/racaljk/hosts/blob/master/hosts' >unbound.local-zone.hosts.conf
echo '# https://github.com/racaljk/hosts' >>unbound.local-zone.hosts.conf
echo '# Thanks to all contributors.' >>unbound.local-zone.hosts.conf
echo '' >>unbound.local-zone.hosts.conf
cat localzone.conf.new | grep '^local-data:' >>unbound.local-zone.hosts.conf
sed -i '5,8d' unbound.local-zone.hosts.conf
```

**Comment by Hongnanjing** [comment]
YOUTU

local-data: "r1---sn-i3b7kn76.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kn76.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kn76.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kn76.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kn76.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kn76.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3beln7r.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3beln7r.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3beln7r.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3beln7r.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3beln7r.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3beln7r.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7kn7r.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kn7r.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kn7r.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kn7r.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kn7r.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kn7r.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7knez.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7knel.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7kner.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7knes.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7kn7d.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kn7d.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kn7d.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kn7d.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kn7d.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kn7d.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7kn7y.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7knee.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7kney.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7knek.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7kned.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7kn7s.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kn7s.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kn7s.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kn7s.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kn7s.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kn7s.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7kn7z.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kn7z.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kn7z.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kn7z.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kn7z.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kn7z.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7kne6.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7knl7.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3beln7d.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3beln7d.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3beln7d.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3beln7d.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3beln7d.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3beln7d.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7kn7k.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kn7k.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kn7k.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kn7k.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kn7k.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kn7k.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r7---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r8---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r9---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r10---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r11---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r12---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r13---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r14---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r15---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r16---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r17---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r18---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r19---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r20---sn-i3b7kne7.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3beln7s.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3beln7s.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3beln7s.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3beln7s.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3beln7s.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3beln7s.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3beln76.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3beln76.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3beln76.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3beln76.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3beln76.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3beln76.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3beln7k.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3beln7k.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3beln7k.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3beln7k.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3beln7k.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3beln7k.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3beln7z.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3beln7z.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3beln7z.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3beln7z.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3beln7z.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3beln7z.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3j5cax-i3bs.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3j5cax-i3bs.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3j5cax-i3bs.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3j5cax-i3bs.googlevideo.com A 218.254.1.13"
local-data: "r5---sn-i3j5cax-i3bs.googlevideo.com A 218.254.1.13"
local-data: "r6---sn-i3j5cax-i3bs.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-i3j5cax-i3bl.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-i3j5cax-i3bl.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-i3j5cax-i3bl.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-i3j5cax-i3bl.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-jna-i3b6.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-jna-i3b6.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-jhi3-i3bl.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-jhi3-i3bl.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-jhi3-i3bl.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-jhi3-i3be.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-jhi3-i3be.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-jhi3-i3be.googlevideo.com A 218.254.1.13"
local-data: "r1---sn-jna-i3bs.googlevideo.com A 218.254.1.13"
local-data: "r2---sn-jna-i3bs.googlevideo.com A 218.254.1.13"
local-data: "r3---sn-jna-i3bs.googlevideo.com A 218.254.1.13"
local-data: "r4---sn-jna-i3bs.googlevideo.com A 218.254.1.13"

**Comment by HighIO** [comment]
可以考虑合并一下这里提到的 hosts 吗 https://github.com/jodrell/unbound-block-hosts/
http://someonewhocares.org/hosts/

**Comment by JWGavin** [comment]
perl2exe转成exe了个人感觉win上用还是方便点，可以考虑把它整合进你的项目方便懒人：http://u.163.com/Gx6XFedn  提取码: 0Jb0wzf0

**Comment by CNMan** [comment]
@HighIO 
帮忙反馈到https://github.com/jedisct1/dnscrypt-proxy/issues/552 后已被添加
https://github.com/jedisct1/dnscrypt-proxy/commit/9563ec4e079176c610cd4548ffcabf4cb8284713

可以参考 #9 生成黑名单
