### ISSUE TITLE
无法打开behance.net

### ISSUE THREAD

**Issue by jhtopone** [CNMan/unbound.conf#20]
其他网站没有发现问题，但是在访问behance的时候显示找不到 www.behance.net 的服务器 DNS 地址。

在 `C:\localdns\unbound\unbound.log` 找到这么一句内容：
```
2017/6/27 16:04:54 C:\localdns\unbound\unbound.exe[3372:0] info: 127.0.0.1 www.behance.net. A IN
2017/6/27 16:04:54 C:\localdns\unbound\unbound.exe[3372:0] info: 127.0.0.1 www.behance.net. A IN REFUSED 0.000000 1 33
```

请问我应该怎么解决

**Comment by CNMan** [comment]
`unbound.local-zone.blacklist.domains.conf`中删掉一行

```
local-zone: "behance.net" always_refuse
```

另外可以向上游数据反馈一下，从源头解决：https://github.com/missdeer/blocklist
