### ISSUE TITLE
跟着操作走发生错误

### ISSUE THREAD

**Issue by JillCheng** [CNMan/unbound.conf#3]
第一次用,跟着操作走,首先无法判断是否在运行.不得已自己点击了unbound.exe来运行,但发生错误.
提示unbound-control.exe不在C:\Program Files (x86),不得已到处找去哪里修改,但还是找不到,

然后是重启重启unbound,CMD反馈"unbound-checkconf"查无此命令

最后,该怎么卸载.放弃了

**Comment by CNMan** [comment]
都是绿色软件，直接删掉即可

**Comment by JillCheng** [comment]
@CNMan 首先非常谢谢提供的开源和hosts。其次很抱歉，我不知道上午是怎么弄的怎么都弄不了，但是我刚刚重新下载在设置了一遍，全部解压完全只放底层的文件，最后成功了。
谢谢

**Comment by CNMan** [comment]
终止进程或把下面命令存为cmd运行
```
@echo off
taskkill /IM dnscrypt-proxy.exe /F
taskkill /IM unbound.exe /F
```

**Comment by JillCheng** [comment]
@CNMan 因为我试另一个防DNS污染的，他们都是要设置127.0.0.1，才能生效。前面使用CNMan的时候，直接结束进程都不能成功。到最后我市删掉所有文件，（忘记有没有重启了）才能使用其他的

**Comment by JillCheng** [comment]
@CNMan 发现设置之后仍然被劫持，出现114导航。比如这个网站http://www.guofs.com/archives/3335

**Comment by CNMan** [comment]
该域名没有A记录，你确定设置成功么？

```bat
Microsoft Windows [版本 6.3.9600]
(c) 2013 Microsoft Corporation。保留所有权利。

C:\Windows\system32>dig www.guofs.com

; <<>> DiG 9.10.3-P4 <<>> www.guofs.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 51688
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.guofs.com.                 IN      A

;; AUTHORITY SECTION:
com.                    860     IN      SOA     a.gtld-servers.net. nstld.verisign-grs.com. 1458716182 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Mar 23 14:57:21 ?D1ú±ê×?ê±?? 2016
;; MSG SIZE  rcvd: 115
```

**Comment by JillCheng** [comment]
![qq 20160323164957](https://cloud.githubusercontent.com/assets/16041103/13980091/849bfaa4-f117-11e5-826a-b4c3527ee7c2.png)
明明进程里有了，设置也没什么错。也的确是127.0.0.1
但是无法完成你上面的操作“dig www.guofs.com”，显示“不是内容文件”等等之类

**Comment by a8l1vy** [comment]
dig命令要另外安装才可在windows下使用。某例 https://teddysun.com/406.html

**Comment by CNMan** [comment]
@ghost 新增了[unbound.bogus-nxdomain.China.conf](https://github.com/CNMan/unbound.conf/blob/master/unbound/unbound.bogus-nxdomain.China.conf)，可以解决重定向到114导航的问题。
如果不起作用，参考[#11](https://github.com/CNMan/unbound.conf/issues/11)补充当地运营商的bogus nxdomain ip
