### ISSUE TITLE
hotmail(outlook)定向出现问题

### ISSUE THREAD

**Issue by JillCheng** [CNMan/unbound.conf#5]
正常情况下，输入hotmail.com或者outlook.com
都能进入微软邮箱。
但是使用unbound.conf 都会定向到bing.com
微软的必应搜索。

只有当我挂上ss或者vpn，才能正常访问。

之前没设置dns没问题，用过一款防dns污染的也没问题

**Comment by CNMan** [comment]
配置里并没有对这两个域名做特殊处理，你再排查一下
