### ISSUE TITLE
关于Unbound 配置文件

### ISSUE THREAD

**Issue by tec1987** [CNMan/unbound.conf#8]
用不着这么复杂的把所有子域名都列出来，直接一条 redirect 就OK了：
local-zone: "google.com" redirect
local-data: xxxx
local-data: xxxx

**Comment by CNMan** [comment]
hosts转换来的，参考 #2 
用redirect会出现问题，有些子域名并非完全都是解析到同一IP

**Comment by tec1987** [comment]
部分子域名可以用 static 来处理，例如：
local-zone: "appspot.l.google.com" static
local-data: "appspot.l.google.com A 74.125.129.141"
local-data: xxxx
...
既然是根据转来的，也无所谓了
